- name: Send Discord Alert
  run: |
    echo "Testing webhook..."

    curl -v -H "Content-Type: application/json" \
         -X POST \
         -d '{"content":"HELLO TEST"}' \
         ${{ secrets.DISCORD_WEBHOOK }}
